from django.contrib import admin
from django.utils.html import format_html
from .models import BusinessHealthScore, MLModelLog


@admin.register(BusinessHealthScore)
class BusinessHealthScoreAdmin(admin.ModelAdmin):
    list_display = (
        'date', 'score_badge', 'label', 'trend_icon',
        'gross_profit_margin', 'expense_to_revenue_ratio',
        'customer_retention_rate', 'created_at'
    )
    list_filter = ('label', 'trend', 'date')
    ordering = ('-date',)
    date_hierarchy = 'date'
    readonly_fields = (
        'score', 'label', 'trend', 'previous_score',
        'gross_profit_margin', 'expense_to_revenue_ratio',
        'inventory_turnover_rate', 'customer_retention_rate',
        'total_sales', 'total_expenses',
        'shap_values', 'recommendations', 'model_version',
        'created_at', 'updated_at'
    )

    fieldsets = (
        ('Score', {'fields': ('date', 'score', 'label', 'trend', 'previous_score')}),
        ('KPI Inputs', {
            'fields': (
                'total_sales', 'total_expenses',
                'gross_profit_margin', 'expense_to_revenue_ratio',
                'inventory_turnover_rate', 'customer_retention_rate'
            )
        }),
        ('AI Explanations', {
            'fields': ('shap_values', 'recommendations', 'model_version'),
            'classes': ('collapse',)
        }),
        ('Meta', {'fields': ('created_at', 'updated_at'), 'classes': ('collapse',)}),
    )

    def score_badge(self, obj):
        score = float(obj.score)
        if score >= 80:
            color = '#27ae60'
        elif score >= 65:
            color = '#2ecc71'
        elif score >= 50:
            color = '#f39c12'
        elif score >= 35:
            color = '#e67e22'
        else:
            color = '#e74c3c'
        return format_html(
            '<span style="background:{};color:white;padding:3px 10px;border-radius:12px;font-weight:bold">{}</span>',
            color, f"{score:.1f}"
        )
    score_badge.short_description = 'Health Score'
    score_badge.admin_order_field = 'score'

    def trend_icon(self, obj):
        icons = {'UP': '▲ Improving', 'DOWN': '▼ Declining', 'STABLE': '— Stable'}
        colors = {'UP': 'green', 'DOWN': 'red', 'STABLE': 'gray'}
        return format_html(
            '<span style="color:{}">{}</span>',
            colors.get(obj.trend, 'gray'),
            icons.get(obj.trend, obj.trend)
        )
    trend_icon.short_description = 'Trend'

    def has_add_permission(self, request):
        return False  # Scores are generated by the ML engine, not manually


@admin.register(MLModelLog)
class MLModelLogAdmin(admin.ModelAdmin):
    list_display = ('version', 'trained_at', 'mae', 'rmse', 'r2_score', 'training_samples', 'is_active')
    list_filter = ('is_active',)
    readonly_fields = ('trained_at',)
    list_editable = ('is_active',)
