# Generated by Django 6.0.6 on 2026-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_business_user_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=150)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("BAR", "Bar"),
                            ("CAFE", "Café"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("ONBOARDED", "Onboarded"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager / Owner"),
                    ("CASHIER", "Cashier"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("IT_ADMIN", "IT Admin"),
                    ("FLOOR_STAFF", "Waiter / Floor Staff"),
                    ("MITCH_HUB", "Mitch Hub Staff"),
                ],
                default="FLOOR_STAFF",
                max_length=20,
            ),
        ),
    ]
