# Generated by Django 6.0.6 on 2026-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_clientrequest_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager / Owner"),
                    ("CASHIER", "Cashier"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("IT_ADMIN", "IT Admin"),
                    ("FLOOR_STAFF", "Waiter / Floor Staff"),
                ],
                default="FLOOR_STAFF",
                max_length=20,
            ),
        ),
    ]
