# Generated by Django 6.0.6 on 2026-07-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0004_alter_customuser_role"),
        ("expenses", "0002_expensereport_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_ai_suggested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_budgets",
                        to="accounts.business",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Budget",
                "verbose_name_plural": "Expense Budgets",
                "ordering": ["month", "category__name"],
                "unique_together": {("business", "category", "month")},
            },
        ),
    ]
