# Generated by Django 6.0.6 on 2026-08-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="served_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("completed", "Completed"),
                    ("voided", "Voided"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
