# Generated by Django 6.0.5 on 2026-05-31 19:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHealthScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("POOR", "Poor"),
                            ("FAIR", "Fair"),
                            ("GOOD", "Good"),
                            ("EXCELLENT", "Excellent"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("UP", "Improving"),
                            ("DOWN", "Declining"),
                            ("STABLE", "Stable"),
                        ],
                        default="STABLE",
                        max_length=10,
                    ),
                ),
                (
                    "previous_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "expense_to_revenue_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "inventory_turnover_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "customer_retention_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("shap_values", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("model_version", models.CharField(default="v1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Health Score",
                "verbose_name_plural": "Business Health Scores",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MLModelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("r2_score", models.FloatField(blank=True, null=True)),
                ("training_samples", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "ML Model Log",
                "verbose_name_plural": "ML Model Logs",
                "ordering": ["-trained_at"],
            },
        ),
    ]
