# Generated by Django 6.0.6 on 2026-07-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_business_user_fk"),
        ("health_score", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesshealthscore",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_scores",
                to="accounts.business",
            ),
        ),
        migrations.AlterField(
            model_name="businesshealthscore",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="businesshealthscore",
            unique_together={("business", "date")},
        ),
    ]
