# Generated by Django 6.0.6 on 2026-07-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_score", "0002_businesshealthscore_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodellog",
            name="version",
            field=models.CharField(max_length=50),
        ),
    ]
