# Generated by Django 6.0.6 on 2026-07-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_business_user_fk"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="accounts.business",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_records",
                to="accounts.business",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryrecord",
            unique_together={("business", "date", "item")},
        ),
    ]
